version: '3'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=development
    container_name: flask-app
    networks:
      - demo-network

networks:
  demo-network:
    external: true