global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['last9-node-exporter:9100']
      
  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask-app:5000']

remote_write:
- url: https://app-tsdb.last9.io/v1/metrics/1573534448a9ee5b0247b39118e527e6/sender/gmail-rockmiop/write
  remote_timeout: 1m
  queue_config:
    capacity: 10000
    max_samples_per_send: 3000
    batch_send_deadline: 20s
    min_shards: 4
    max_shards: 200
    min_backoff: 100ms
    max_backoff: 10s
  basic_auth:
    username: 1e2d74b8-401c-4032-b11a-e2dd122dbb39
    password: 79f1cbc5d352dc8904e8bb23d16ddb63